In [1]:
from numpy import random

x = random.randint(200)
print(x)

34


In [2]:
from numpy import random  

x = random.rand()
print(x)

0.7883859386843393


In [3]:
from numpy import random

x = random.randint(100, size=(5))
print(x)

[70 16 90 58 17]


In [4]:
from numpy import random

x = random.randint(200, size=(3, 5))
print(x)

[[ 29  59 173 157 133]
 [190 173  24 191 122]
 [ 94  37 155 133 129]]


In [5]:
from numpy import random

x = random.rand(5)
print(x)

[0.87869875 0.92677835 0.78574953 0.6908526  0.12014828]


In [6]:
from numpy import random

x = random.rand(3, 5)
print(x)

[[0.07994053 0.36349025 0.33947798 0.06242842 0.78038547]
 [0.06294218 0.00971602 0.87202774 0.56338671 0.06243431]
 [0.19361723 0.32370071 0.26113698 0.30946878 0.23689816]]


In [7]:
from numpy import random

x = random.choice([3, 5, 7, 9])
print(x)

3


In [8]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[7 3 3 3 3]
 [7 7 9 7 5]
 [5 7 5 3 7]]


In [9]:
from numpy import random

# Define values and their probabilities
values = [3, 5, 7, 9]
probabilities = [0.1, 0.3, 0.6, 0.0]

# Generate a 1-D array with 100 values based on probabilities
x = random.choice(values, p=probabilities, size=(100))

print(x)

[7 7 7 7 7 7 7 7 7 7 7 3 7 7 5 3 7 7 7 5 5 7 3 5 7 7 3 7 7 3 7 7 3 5 5 7 5
 3 7 7 7 5 7 5 7 5 7 3 5 3 7 7 7 7 7 7 5 7 7 7 5 5 7 5 3 7 7 5 7 7 5 7 5 7
 5 7 7 3 7 7 3 5 7 7 7 7 7 3 7 7 7 7 7 5 7 7 3 7 5 7]


In [10]:
from numpy import random

# Define values and their probabilities
values = [3, 5, 7, 9]
probabilities = [0.1, 0.3, 0.6, 0.0]

# Generate a 2-D array with 3 rows and 5 columns based on probabilities
x = random.choice(values, p=probabilities, size=(3, 5))

print(x)

[[5 7 7 5 7]
 [7 5 7 3 5]
 [7 5 3 7 3]]


In [11]:
from numpy import random
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Shuffle the array in-place
random.shuffle(arr)

# Print the shuffled array
print(arr)

[4 5 1 3 2]


In [12]:
from numpy import random
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Generate a random permutation of the array
permuted_arr = random.permutation(arr)

# Print the random permutation
print(permuted_arr)

[1 5 3 4 2]
